# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minio.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bminio.proto\x12\x0bminio_proto\"\x0e\n\x0c\x45mptyRequest\"\x14\n\x04User\x12\x0c\n\x04user\x18\x01 \x01(\t\":\n\x0b\x46ileRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"K\n\x0e\x46ileAddRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"?\n\x06Status\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\x08\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\"d\n\x10\x46ileInfoResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12#\n\x06status\x18\x04 \x01(\x0b\x32\x13.minio_proto.Status\"A\n\x0c\x46ileResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x13.minio_proto.Status2\xda\x04\n\x0cMinioMethods\x12\x43\n\x0f\x43heckConnection\x12\x19.minio_proto.EmptyRequest\x1a\x13.minio_proto.Status\"\x00\x12\x35\n\tCheckUser\x12\x11.minio_proto.User\x1a\x13.minio_proto.Status\"\x00\x12\x33\n\x07\x41\x64\x64User\x12\x11.minio_proto.User\x1a\x13.minio_proto.Status\"\x00\x12\x36\n\nDeleteUser\x12\x11.minio_proto.User\x1a\x13.minio_proto.Status\"\x00\x12H\n\x10GetFilesInfoList\x12\x11.minio_proto.User\x1a\x1d.minio_proto.FileInfoResponse\"\x00\x30\x01\x12L\n\x13\x44ownloadFileVersion\x12\x18.minio_proto.FileRequest\x1a\x19.minio_proto.FileResponse\"\x00\x12\x44\n\x0e\x41\x64\x64\x46ileVersion\x12\x1b.minio_proto.FileAddRequest\x1a\x13.minio_proto.Status\"\x00\x12\x44\n\x11\x44\x65leteFileVersion\x12\x18.minio_proto.FileRequest\x1a\x13.minio_proto.Status\"\x00\x12=\n\nDeleteFile\x12\x18.minio_proto.FileRequest\x1a\x13.minio_proto.Status\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minio_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYREQUEST._serialized_start=28
  _EMPTYREQUEST._serialized_end=42
  _USER._serialized_start=44
  _USER._serialized_end=64
  _FILEREQUEST._serialized_start=66
  _FILEREQUEST._serialized_end=124
  _FILEADDREQUEST._serialized_start=126
  _FILEADDREQUEST._serialized_end=201
  _STATUS._serialized_start=203
  _STATUS._serialized_end=266
  _FILEINFORESPONSE._serialized_start=268
  _FILEINFORESPONSE._serialized_end=368
  _FILERESPONSE._serialized_start=370
  _FILERESPONSE._serialized_end=435
  _MINIOMETHODS._serialized_start=438
  _MINIOMETHODS._serialized_end=1040
# @@protoc_insertion_point(module_scope)
